# Generated by Django 3.2.3 on 2021-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_details',
            fields=[
                ('cdid', models.AutoField(primary_key=True, serialize=False)),
                ('cdnm', models.CharField(max_length=100)),
                ('cdimg', models.CharField(default='', max_length=100)),
                ('cdtype', models.CharField(max_length=100)),
                ('cdprice', models.IntegerField()),
                ('cdquantity', models.IntegerField()),
            ],
            options={
                'db_table': 'card_details',
            },
        ),
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cpass', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=254)),
                ('ccontact', models.IntegerField()),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('cdid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('b_cdquantity', models.IntegerField()),
                ('cdprice', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('d_address', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='rate_review',
            fields=[
                ('rrid', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('cdid', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
            options={
                'db_table': 'rt_n_rv',
            },
        ),
    ]
